version: 2

project_name: helm-upgrade-check-plugin

env_files:
  github_token: ~/.config/goreleaser/helm-upgrade-check-plugin-github-token

before:
  hooks:
    - go mod tidy
    # Ensure Helm is present in the build environment to generate signatures later
    - helm version --short
    - ./build-scripts/check-gpg-keyring.sh

builds:
  - id: helm-upgrade-check-plugin
    main: ./cmd/helm-upgrade-check
    binary: helm-upgrade-check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: ./build-scripts/package-plugin.sh
          env:
            - GORELEASER_TARGET={{ .Target }}
            - GORELEASER_BINARY_PATH={{ .Path }}
            - GORELEASER_VERSION={{ .Version }}
            - GPG_KEY_NAME={{ .Env.GPG_KEY_NAME }}
            - PASSPHRASE_FILE={{ .Env.SECURE_PASS_FILE }}
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - INSTALL.md
      - plugin.yaml
      - scripts/**/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bcurnow
    name: helm-upgrade-check-plugin
  draft: false
  prerelease: "false"
  extra_files:
    - glob: './dist/*.tgz.prov'
    - glob: './dist/*.tgz'