version: 2

project_name: helm-upgrade-check-plugin

before:
  hooks:
    - go mod tidy
    # Ensure Helm is present in the build environment to generate signatures later
    - helm version --short

builds:
  - id: helm-upgrade-check-plugin
    main: ./cmd/helm-upgrade-check
    binary: helm-upgrade-check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - INSTALL.md
      - plugin.yaml
      - scripts/**/*
publishers:
  - name: helm-provenance-generator
    ids:
      - helm-plugin-archive
    cmd: |
      mkdir -p temp_sign
      tar -xzf {{ abs .ArtifactPath }} -C temp_sign
      helm plugin package --sign --key "${GPG_KEY_NAME}" ./temp_sign/*
      mv *.tgz "{{ abs .ArtifactDir }}/upgrade-check-{{ .Version }}.tgz"
      mv *.tgz.prov "{{ abs .ArtifactDir }}/upgrade-check-{{ .Version }}.tgz.prov"
      rm -rf temp_sign      

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

env_files:
  github_token: ~/.config/goreleaser/helm-upgrade-check-plugin-github-token

release:
  github:
    owner: bcurnow
    name: helm-upgrade-check-plugin
  draft: false
  prerelease: "false"
  extra_files:
    - glob: './dist/*.tgz.prov'
    - glob: './dist/*.tgz'